server:
  port: ${PORT}

spring:
  application:
    name: store
  profiles:
    active: local

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  client:
    config:
      default:
        readTimeout: 60000
        connectTimeout: 60000


#Custom configuration
base:
  directory: classpath:config/

auth:
  jwt:
    issuer: http://sample.com
    secret-key: abc123

