server:
  port: ${PORT:8080}

spring:
  application:
    name: ${APP:store}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: ${DATABASE_HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  client:
    config:
      default:
        readTimeout: 60000
        connectTimeout: 60000


#Custom configuration
base:
  directory: classpath:config/

auth:
  jwt:
    issuer: http://sample.com
    secret-key: abc123

