# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [ created ]
  # run manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Set up archived Oracle JDK 17.0.1'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: 17.0.1

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} publish

